### ISSUE TITLE
Questions regarding requirements

### ISSUE THREAD

**Issue by himabindugit** [Superformula/cloud-backend-test#19]
1. Can I assume the full address is given when client making Query?
2. Do you any AWS account i can use to deploy the service
3. When I am exploring, i saw couple of node modules to get longitude, latitude which requires Google API key in Google cloud. Do you have API key already existing or should i create a new one? If I create a new one, how can I share sensitive info?

**Comment by marcelino-sf** [comment]
Hi @himabindugit,

Thanks for the questions.

1. Yes, but make sure to have it documented in the README or somewhere else. Please treat this as a real-world task, when you create a new API for another team to consume, how would you normally do?
2. We don't provide an AWS account for that, you would need to have a personal one
3. We don't provide the API key either. Since it's a sensitive value, you need to make sure this is not exposed to anyone but you

Feel free to ask any other questions in this thread, I'll keep it open until you finally submit the Pull Request 😊

**Comment by himabindugit** [comment]
Just want to update you all, by the end-of-today, i have below api gateway working, more pieces are still need to implement, so it is like WIP
<img width="1376" alt="Screen Shot 2022-08-08 at 6 15 20 PM" src="https://user-images.githubusercontent.com/22843777/183524037-b7eb7304-79b1-46d9-aa55-e5d64c7c2ccb.png">

**Comment by himabindugit** [comment]
My git user have given right permissions for be able to push to this repo? my user is `himabindugit`

**Comment by marcelino-sf** [comment]
You will need to [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the repository and create a Pull Request

**Comment by himabindugit** [comment]
Hi, by Eod today - i just want to let you know where i am

- i am just cleaning up code
- Reading README one more time just to make sure i cover everything and
- Since i have cut the branch from this repo and i just need to ship changes to my forked repo

Most probably by tomorrow, i can open PR

**Comment by himabindugit** [comment]
Hi, just want to give you an update
I have finished writing documentation, by following my docs just making sure if i can deploy service fine on a different machine, once i confirm/adjust docs based on the outcomes, i can open PR by EOD or early tomorrow.

**Comment by himabindugit** [comment]
@marcelino-sf Finally opened PR https://github.com/Superformula/cloud-backend-test/pull/22

**Comment by marcelino-sf** [comment]
Thank you, Hima! We're going to review it as soon as possible
